<a href="https://colab.research.google.com/github/sush0037/my-portfolio/blob/master/practice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing the module
import numpy as np



In [2]:
#numpy works with array [list into array]
my_list = [1,2,3]
type(my_list)

list

In [3]:
#converting list into array
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [4]:
print(my_array)

[1 2 3]


In [5]:
my_list_1 = [1,2,3]
my_list_2 = [4,5,6]
my_list_3 = [7,8,9]
arr_2d = np.array([my_list_1,my_list_2,my_list_3])
print (arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr_2d.shape

(3, 3)

In [7]:
arr_2d.ndim

2

In [10]:
arr = np.array([1,2,3,4,5])
print(arr[:-1])  # Output: 6 (row 1, column 2)


[1 2 3 4]


In [12]:
arr_2d[:1,2]
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print (b)
print(b[0,0:4,1:4] ) #layers,rows, columns


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
